name: 'Test Deploy'

on:
  push:
    branches:
      - main
  issues:
    types: [opened, edited, milestoned]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          fetch-depth: 20
          lfs: 1
      - name: set lint
        run: echo "linting...."
      - name: set test
        run: echo "testing..."
      - name: build
        run: echo "building..."
