name: 'get and cache dependancies'
description: 'Get dependancies via npm'
runs:
  using: 'composite' # default
  steps:
    - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash # Extra setting using the type of shell to be used
