name: Deploy website
on:
  push:
    branches:
      - main
      - dev
      - test
      - new

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test 
        uses: actions/checkout@v3
      - name: cache dependancies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - run: |
          cd 3_test
          ls -a
          npm ci
          npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build code gen artifacts
        uses: actions/checkout@v3
      - name: cache dependancies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - run: |
          cd 3_test
          ls -a
          npm ci
          npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: 3_test/dist
          # path: |
          #   3_test/dist
          #   3_test/package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Deploy
        run: echo "Deploying..."
