name: Deploy website
on:
  push:
    branches:
      - main
      - dev
      - test
      - new
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - run: |
          cd 3_test
          ls -a
          npm ci
          npm run test
          npm run build
      - name: upload artifacr
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            3_test/dist
            3_test/package.json

      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - run: |
          cd 3_test
          echo "testing"
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
