---
name: reusable workflow

on: 
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: I am improted from another workflow
          run: echo "deploying from a reusable worklflow"
