name: 'Matrix Demo'
on:
  push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
          - node-version: 12
            operating-system: ubuntu-latest
          - node-version: 14
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build

  deploy:
    uses: ./.github/workflows/resuable.yml
